### ISSUE TITLE
Add Angular dependencies to `peerDependencies`

### ISSUE THREAD

**Issue by patrickarlt** [tomwayson/angular2-esri-loader#17]
When `angular-esri-loader` is included in a project and bundled (like with webpack) it is including its own copies of some code from `@angular` as evidenced by this screencap of `source-map-explorer`:

![build assets js 0 chunk js source map explorer 4](https://cloud.githubusercontent.com/assets/378557/26223247/2a6be9ac-3bd2-11e7-925a-71cd6c68bd30.png)

I think the accepted pattern is to specify the Angular dependencies in BOTH `peerDependencies` and `devDependencies` like now `ngx-datatable` does it https://github.com/swimlane/ngx-datatable/blob/master/package.json#L66-L137. This should tell NPM that `angular-esri-loader` needs a `peerDependency` of `@angular/core` when being installed as a dependency as opposed to installing a specific version.

@noahmulfinger or @araedavis you should be able to take care of this.

**Comment by TheKeithStewart** [comment]
Thanks for pointing this out, @patrickarlt! 

Once we have landed #16 we will take a look at this issue and see what we need to do.

**Comment by tomwayson** [comment]
@patrickarlt since I'm no longer using Angular, I can't keep up w/ what's an accepted pattern or not. Basically, I'm at the point where the only role I can play in this repo is to push green buttons on PRs that have 2 or more 👍.

So, I can merge and release whatever y'all come up w/, or if someone wants to relieve me of that duty, I'm glad to transfer ownership.

**Comment by patrickarlt** [comment]
Appears to be resolved in the latest build.
