### ISSUE TITLE
Allow Angular 2 or 4

### ISSUE THREAD

**Issue by patrickarlt** [tomwayson/angular2-esri-loader#18]
It would be really nice to be able to use the latest and greatest of this without having to upgrade our whole app to Angular 4. Since this only requires `NgModule` and `Injectable` from `@angular/core` it should be as simple as making the version something like `"angular/core": ^2.0.0 || ^4.0.0` in `package.json`

<img width="1004" alt="screenshot 2017-05-18 14 02 19" src="https://cloud.githubusercontent.com/assets/378557/26223438/e2c9be20-3bd2-11e7-8332-a1f200fcad06.png">

@noahmulfinger or @araedavis you should be able to take care of this.

**Comment by TheKeithStewart** [comment]
@patrickarlt We are in the process of reworking this library to use a proper NgModule structure in #16. There was an attempt to use this in an Angular application that was still in version 2 but there were some mysterious errors. Because of this we are moving towards having two versions of this library, one for V2 and one for V4 and above. 

Going forward we intend to do something along the lines of what you are suggesting to support multiple versions of Angular.

**Comment by tomwayson** [comment]
I'm all for whatever y'all come up w/ for this.

**Comment by patrickarlt** [comment]
@TheKeithStewart seems like a fine approach to me as documented so I'll close this out.
