### ISSUE TITLE
Document how to get proper types

### ISSUE THREAD

**Issue by patrickarlt** [tomwayson/angular2-esri-loader#2]
@tomwayson after a bit of experimentation I figured out how to properly use the Typescript definitions for the JS API and I think we should document it here for users.

For JS API 3.x

* `npm install @types/arcgis-js-api` (for Typescript 2.0) or [install with typings](https://github.com/Esri/jsapi-resources/tree/master/3.x/typescript) for Typescript 1.x.
* Now you can access the Typings under the  `__esri` namespace like `__esri.Map`.

For JS API 4.x

* [Download the 4.x Typings](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts) and put them somewhere Typescript can find them usually in your source folder, I like using `src/@types`.
* Now you can access the Typings under the  `__esri` namespace like `__esri.Map`.

The updated `EsriMapComponent` looks like this:

```ts
import { Component, OnInit, ViewChild, ElementRef } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-esri-map',
  templateUrl: './esri-map.component.html',
  styleUrls: ['./esri-map.component.css']
})
export class EsriMapComponent implements OnInit {
  @ViewChild('map') mapEl: ElementRef;

  map: __esri.Map; // VS Code (and others) will now autocomplete on `this.map` like a boss.

  constructor(private route: ActivatedRoute) {}

  ngOnInit() {
    if (this.map) {
      // map is already initialized
      return;
    }
    // get the required esri classes from the route
    const esriModules = this.route.snapshot.data['esriModules'];
    this._createMap(esriModules);
  }

  // create a map at the root dom node of this component
  _createMap([Map]) {
    this.map = new Map(this.mapEl.nativeElement, {
      center: [-118, 34.5],
      zoom: 8,
      basemap: 'dark-gray'
    });
  }
}
```

**Comment by patrickarlt** [comment]
@tomwayson If you assign this to me I will update the readme :)

**Comment by tomwayson** [comment]
Thanks @patrickarlt! all yours

**Comment by jwasilgeo** [comment]
@andygup good things are happening in the world

**Comment by maxkisung** [comment]
FYI, npm install @types/arcgis-js-api now installs typings for 4.2.0

**Comment by tomwayson** [comment]
Thanks @maxkisung. Looks like from `npm info @types/arcgis-js-api` the 3.x releases are all published too, so for 3.x it's probably a matter of `npm i @types/arcgis-js-api@3.19.0`.

It sounds like you have recent experience w/ this. I would gladly accept a PR adding the steps you followed to the README. 😉

**Comment by jwasilgeo** [comment]
@patrickarlt @maxkisung can you explain to me why the typings for JSAPI 3.x aren't using a `namespace`?

For example, I see in the 4.x typings that it does explicitly list the [`__esri` namespace](https://github.com/Esri/jsapi-resources/blob/master/4.x/typescript/arcgis-js-api.d.ts#L32).

I am working on getting the documentation figured out to close out this particular issue, but since I am working with JSAPI 3.19 (i.e. `npm install @types/arcgis-js-api@3.19.0`) my VSCode claims it doesn't know anything about the `__esri` namespace.

Is there something else I need to do (in addition to making sure arcgis-js-api typings are/n't excluded in my project's **tsconfig.json**)?

Does the 3.x **arcgis-js-api.d.ts** file need to have this namespace declaration, too?

**Comment by tomwayson** [comment]
@jwasilgeo 

Thanks for taking this on.

At this point, I'm thinking the way to resolve this issue is to just add a note to the README saying that if you want types you'll have to install them as per the instructions for whichever version of the ArcGIS API for JavaScript that you are using:

https://github.com/Esri/jsapi-resources/tree/master/4.x/typescript
https://github.com/Esri/jsapi-resources/tree/master/3.x/typescript

If people have issues like the one you're experiencing, they should open them over there. In fact, I suggest you do that.

**Comment by jwasilgeo** [comment]
Thanks for the guidance and advice, @tomwayson. I'll proceed as you have suggested.

**Comment by tomwayson** [comment]
Opened a PR for this. It's like I forgot how GitHub works.
