### ISSUE TITLE
Question - Suggestions about implementing point clustering

### ISSUE THREAD

**Issue by mechachi** [tomwayson/angular2-esri-loader#24]
I've seen some examples about implementing clustering via esri-system-js or https://github.com/nickcam/FlareClusterLayer. Are there any suggestions as to the best approach to get a clustering layer working with angular-esri-loader?

**Comment by tomwayson** [comment]
It looks like that repo includes the [built output](https://github.com/nickcam/FlareClusterLayer/blob/master/fcl/FlareClusterLayer_v4.js) as an (unminified) AMD module. That should be something that angular-esri-loader can load via `loadModules`. 

The question is, where should it be loaded from? If you download or npm install it, you'd have to specify a path to the file that is going to exist in the build output. Looks like angular-cli does have [some config setting you can use to tell it which vendor files to include in the output](https://stackoverflow.com/questions/35690663/how-to-add-a-third-party-library-when-using-angular-cli). If you're not using angular-cli, then you'd have to figure out how to do that via whatever build system you're using. Either way, once you have the path, you would just [configure dojo](https://dojotoolkit.org/documentation/tutorials/1.10/dojo_config/) with the path so that it could be resolved like `esriLoader.loadModules(['fcl/FlareClusterLayer_v4']).then(([FlareClusterLayer]) => {...})`.

@nickcam may have more ideas.

**Comment by nickcam** [comment]
Hi Guys,

I haven't used angular-esri-loader, just esri-system-js, so can't help with loading it using that sorry.

As Tom points out the built javascript amd module is included so any app (javascript or typescript) can load it up just like any other amd module.

I'm using it in an angular 4 app and I just copy the [FlareClusterLayer_v4.ts](https://github.com/nickcam/FlareClusterLayer/blob/master/typescript/FlareClusterLayer_v4.ts) file into my project so it gets compiled and built with the rest of the project. It's a bit crude but is simple and works. You just need to make sure you've got all of the esri and dojo modules it uses loaded in your project. 

Really I should just create an npm package...one day maybe :).

Thanks,
Nick

**Comment by tomwayson** [comment]
> I'm using it in an angular 4 app and I just copy the FlareClusterLayer_v4.ts file into my project so it gets compiled and built with the rest of the project.

FYI I don't think that will work in an esri-loader app.

**Comment by nickcam** [comment]
Ok, fair enough. Best to stick with Tom's suggestions :smile:.

**Comment by kevhae** [comment]
I'm having the exact same issue and would love to see how this works with an angular4 cli + esri-loader app.

**Comment by tomwayson** [comment]
FYI - looks like @tomasvoj had success with the approach I suggested above in #32 

In his case, he was using his own Dojo modules instead of third party ones like FlareClusterLayer, but [the solution](https://github.com/tomwayson/angular-esri-loader/issues/32#issuecomment-337803304
) is the same.

**Comment by tomwayson** [comment]
closing this since we're deprecating this repo (#37) and there are links to a few solutions above.
