### ISSUE TITLE
click event on GraphicsLayer

### ISSUE THREAD

**Issue by LudoFont** [tomwayson/angular2-esri-loader#31]
Hello,

I followed the angular CLI gist, all is working great, and I'm currently trying to trigger click events on a GraphicsLayer that I added to the map.
There is no way to trigger this event, and I can't figure out why.
The code I put in the esri-map.component.ts :
```
  ...
  public ngOnInit() {
   ...
        const mapProperties: __esri.MapProperties  = {
          basemap: 'streets'
        };

        const map = new Map(mapProperties);

        const mapViewProperties: __esri.MapViewProperties = {
          // create the map view at the DOM element in this component
          container: this.mapViewEl.nativeElement,
          center: [165.69, -21.20],
          zoom: 7,
          map
        };
        this.mapView = new MapView(mapViewProperties);

        var points = [
          {x: 166.454, y:-22.306},
          {x: 166.442, y:-22.291},
          {x: 166.457, y:-22.29},
          {x: 166.4356, y:-22.3026}
        ];

        var layer = new GraphicsLayer();

        points.forEach(point => {
          let g = new Graphic({
            geometry: new Point({
              x: point.x,
              y: point.y
            }),
            attributes: {
              index: 0
            },
            symbol: new PictureMarkerSymbol({
              url: 'http://www.myiconfinder.com/uploads/iconsets/256-256-a5485b563efc4511e0cd8bd04ad0fe9e.png',
              width: 20,
              height: 20,
              yoffset: 10
            })
          });

          layer.add(g);
        });

        layer.on('click', function(){
          console.log("click");
        });

        map.layers.add(layer);
      });
    });
  }

}

```

And i got this error :
```
Failed to compile.
C:/dev/workspace/poc-sig/src/app/esri-map/esri-map.component.ts (105,23): Argument of type '"click"' is not assignable to parameter of type '"layerview-destroy"'.
```

I don't understand what is wrong, this is a working example of a similar action in JavaScript (log is ok in console) : http://jsfiddle.net/uphyh41h/

Thank you,

Ludovic

**Comment by jwasilgeo** [comment]
I am pretty sure this has to do with the ArcGIS API for JavaScript, and not anything to do with TS, Angular, or this lib.  The jsfiddle points to a working example with v3.x, but you're writing and using v4.x of the ArcGIS API for JavaScript.  Mouse interaction listeners are quite different in this version.

The error I think is because there are [only 2 (documented) events](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-GraphicsLayer.html#events-summary) you can listen to from the `GraphicsLayer`.

I suggest you listen for a click on the `MapView` in v4.x.

https://developers.arcgis.com/javascript/latest/sample-code/layers-scenelayer-query-popup/index.html?search=click%20event

https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#event:click

**Comment by andygup** [comment]
@LudoFont adding onto Jacob's comments, I'd also recommend using the [`hitTest()`](https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#hitTest) pattern to check for graphics in a `GraphicsLayer` or `FeatureLayer`. Here's a sample: https://developers.arcgis.com/javascript/latest/sample-code/view-hittest/index.html

```javascript

// Get the screen point from the view's click event
view.on("click", function(event){
    var screenPoint = {
       x: event.x,
       y: event.y
    };

    // Search for graphics at the clicked location 
    view.hitTest(screenPoint).then(function(response){
        if(response.results[0].graphic){
           console.log("Top graphic found! Here it is: ", response.results[0].graphic);
        }
    });
})

```
